name: Code Coverage
on:
    push:
    # only trigger if theres a change in src/ directory
        paths:
            - '.github/workflows/code-coverage.yml'
            - 'clover.xml'
    pull_request:
        paths:
            - '.github/workflows/code-coverage.yml'
            - 'clover.xml'
    workflow_dispatch:

permissions:
  contents: write
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Generate code coverage badge
        run: php bin/generate-coverage-badge.php clover.xml coverage.svg

      - name: Setup SSH Signing
        run: |
          # Create the key file from the secret
          echo "${{ secrets.SSH_SIGNING_KEY }}" > sign_key
          chmod 600 sign_key
          
          # Configure Git to use SSH for signing
          git config --global user.name 'Erik Pöhler'
          git config --global user.email 'admin@teuton.mx'
          git config --global gpg.format ssh
          git config --global user.signingkey "$(pwd)/sign_key"
          git config --global commit.gpgsign true

      - name: Commit badge
        run: |
            git add coverage.svg
            git commit -am "chore: coverage.svg badge updated" --no-verify
            git push --no-verify
        continue-on-error: true # do not fail if nothing changed